{
 "title": "Synology NAS Overview",
 "description": "The Synology NAS Overview dashboard gives an overall glance at multiple Synology NAS systems and their operational status.",
 "tags": [
  "synology",
  "dsm"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(ssCpuUser, job)" } },
   {
    "name": "instance",
    "label": "host",
    "query": {
     "query": "query_result(ssCpuUser{job=~'$job'})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modelName{job=~'$job',instance=~'$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Serial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "serialNumber{job=~'$job',instance=~'$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "description": "The percentage of CPU time spent processing user-level code, calculated over the last minute.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ssCpuIdle{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 / memTotalReal{job=~'$job',instance=~'$instance'}) * (memTotalReal{job=~'$job',instance=~'$instance'} - memAvailReal{job=~'$job',instance=~'$instance'} - memCached{job=~'$job',instance=~'$instance'} - memBuffer{job=~'$job',instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(memTotalSwap{job=~'$job',instance=~'$instance'} - memAvailSwap{job=~'$job',instance=~'$instance'}) / memTotalSwap{job=~'$job',instance=~'$instance'} * 100"
    }
   ]
  },
  {
   "title": "System Temp",
   "type": "gauge",
   "description": "The temperature of Disk Station uses Celsius degree",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Volume 1 Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"})",
     "legendFormat": "Volume 1"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=~'$job',instance=~'$instance'} / 100"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memTotalReal{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memTotalSwap{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "system status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemStatus{job=~'$job',instance=~'$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "powerStatus{job=~'$job',instance=~'$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu fan status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuFanStatus{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System fan status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemFanStatus{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Connected Users / Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "serviceUsers{job=~'$job',instance=~'$instance'}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "laLoadInt{job=~\"$job\",instance=~'$instance'}",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalReal{instance=~'$instance',job=~\"$job\"} - (memShared{instance=~'$instance',job=~\"$job\"} + memCached{instance=~'$instance',job=~\"$job\"} + memBuffer{instance=~'$instance',job=~\"$job\"} + memAvailReal{instance=~'$instance',job=~\"$job\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "memAvailReal{instance=~'$instance',job=~\"$job\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "memBuffer{instance=~'$instance',job=~\"$job\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "memCached{instance=~'$instance',job=~\"$job\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "memShared{instance=~'$instance',job=~\"$job\"}",
     "legendFormat": "Shared"
    },
    {
     "expr": "memTotalReal{instance=~'$instance',job=~\"$job\"} ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalReal{instance=~'$instance',job=~\"$job\"} + memTotalSwap{instance=~'$instance',job=~\"$job\"} - memTotalFree{instance=~'$instance',job=~\"$job\"}",
     "legendFormat": "Used Virtual Memory"
    },
    {
     "expr": "memTotalFree{instance=~'$instance',job=~\"$job\"}",
     "legendFormat": "Free Virtual Memory"
    },
    {
     "expr": "memTotalReal{instance=~'$instance',job=\"$job\"} + memTotalSwap{instance=~'$instance',job=\"$job\"}",
     "legendFormat": "Total Virtual Memory"
    }
   ]
  },
  {
   "title": "S.M.A.R.T Disk Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "S.M.A.R.T Disk Failures",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "diskSMARTAttrStatus{job=~'$job',instance=~'$instance',diskSMARTAttrStatus!=\"OK\"}",
     "legendFormat": "AttrStatus"
    },
    {
     "expr": "diskSMARTInfoDevName{job=~'$job',instance=~'$instance'}",
     "legendFormat": "InfoDevName"
    },
    {
     "expr": "diskSMARTAttrName{job=~'$job',instance=~'$instance'}",
     "legendFormat": "AttrName"
    },
    {
     "expr": "diskSMARTAttrCurrent{job=~'$job',instance=~'$instance'}",
     "legendFormat": "AttrCurrent"
    },
    {
     "expr": "diskSMARTAttrThreshold{job=~'$job',instance=~'$instance'}",
     "legendFormat": "AttrThreshold"
    },
    {
     "expr": "diskSMARTAttrWorst{job=~'$job',instance=~'$instance'}",
     "legendFormat": "AttrWorst"
    }
   ]
  },
  {
   "title": "Storage Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Storage Information",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "raidTotalSize{job=~'$job',instance=~'$instance'}",
       "legendFormat": "Total Size"
      },
      {
       "expr": "(raidTotalSize{job=~'$job',instance=~'$instance'}-raidFreeSize{job=~'$job',instance=~'$instance'})",
       "legendFormat": "Used"
      },
      {
       "expr": "raidFreeSize{job=~'$job',instance=~'$instance'}",
       "legendFormat": "Free"
      },
      {
       "expr": "raidStatus{job=~'$job',instance=~'$instance'}",
       "legendFormat": "Free"
      },
      {
       "expr": "((raidTotalSize{job=~'$job',instance=~'$instance'}-raidFreeSize{job=~'$job',instance=~'$instance'})/raidTotalSize{job=~'$job',instance=~'$instance'})*100",
       "legendFormat": "Usage by Percent"
      }
     ]
    },
    {
     "title": "Volume Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(spaceIONReadX{instance=~'$instance',job=~\"$job\"}[5m])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(spaceIONWrittenX{instance=~'$instance',job=~\"$job\"}[5m])",
       "legendFormat": "Written Bytes"
      }
     ]
    },
    {
     "title": "Volume IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(spaceIOReads{instance=~'$instance',job=~\"$job\"}[5m])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(spaceIOWrites{instance=~'$instance',job=~\"$job\"}[5m])",
       "legendFormat": "Written Bytes"
      }
     ]
    },
    {
     "title": "Free Space Percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "((raidTotalSize{job=~'$job',instance=~'$instance'}-raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"})/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"})",
       "legendFormat": "{{raidName}}"
      }
     ]
    },
    {
     "title": "Free Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"}",
       "legendFormat": "{{raidName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Drives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Hard Drive and SSD Information",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "diskIndex{job=~'$job',instance=~'$instance'}"
      },
      {
       "expr": "diskID{job=~'$job',instance=~'$instance'} "
      },
      {
       "expr": "diskType{job=~'$job',instance=~'$instance'}"
      },
      {
       "expr": "diskStatus{job=~'$job',instance=~'$instance'}"
      },
      {
       "expr": "diskModel{job=~'$job',instance=~'$instance'}"
      },
      {
       "expr": "(diskTemperature{job=~'$job',instance=~'$instance'})"
      }
     ]
    },
    {
     "title": "Device Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(storageIONReadX{instance=~'$instance',job=~\"$job\"}[5m])",
       "legendFormat": "{{storageIODevice}}__readBytes"
      },
      {
       "expr": "rate(storageIONWrittenX{instance=~'$instance',job=~\"$job\"}[5m])",
       "legendFormat": "{{storageIODevice}}__writtenBytes"
      }
     ]
    },
    {
     "title": "Device IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(storageIOReads{instance=~'$instance',job=~\"$job\"}[5m])",
       "legendFormat": "{{storageIODevice}}__read"
      },
      {
       "expr": "irate(storageIOWrites{instance=~'$instance',job=~\"$job\"}[5m])",
       "legendFormat": "{{storageIODevice}}__write"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Physical Network Interface Information",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "ifPhysAddress{job=~'$job',instance=~'$instance',ifName=~'eth0|eth3|eth5'}"
      },
      {
       "expr": "ifAdminStatus{job=~'$job',instance=~'$instance',ifName=~'eth0|eth3|eth5'}"
      },
      {
       "expr": "ifSpeed{job=~'$job',instance=~'$instance',ifName=~'eth0|eth3|eth5'}"
      },
      {
       "expr": "ifOperStatus{job=~'$job',instance=~'$instance',ifName=~'eth0|eth3|eth5'}"
      },
      {
       "expr": "ifAlias{job=~'$job',instance=~'$instance',ifName=~'eth0|eth3|eth5'}"
      },
      {
       "expr": "ifMtu{job=~'$job',instance=~'$instance',ifName=~'eth0|eth3|eth5'}"
      }
     ]
    },
    {
     "title": "Input [daily sum]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase(ifHCInOctets{job=~'$job',instance=~'$instance', ifName=~\"eth0|eth3|eth5\"}[24h] offset -1d)",
       "legendFormat": "{{ifName}}"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(ifHCInOctets{job=~'$job',instance='$instance', ifName=~\"eth0|eth3|eth5\"}[5m]) or rate(ifInOctets{job='$job',instance=~'$instance', ifName=~\"eth0|eth3|eth5\"}[5m]) ",
       "legendFormat": "{{ifName}}__in"
      },
      {
       "expr": "rate(ifHCOutOctets{job=~'$job',instance=~'$instance', ifName=~\"eth0|eth3|eth5\"}[5m]) or rate(ifOutOctets{job='$job',instance='$instance', ifName=~\"eth0|eth3|eth5\"}[5m]) ",
       "legendFormat": "{{ifName}}__out"
      }
     ]
    },
    {
     "title": "Output [daily sum]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase(ifHCOutOctets{job=~'$job',instance=~'$instance', ifName=~\"eth0|eth3|eth5\"}[24h] offset -1d)",
       "legendFormat": "{{ifName}}"
      }
     ]
    }
   ]
  }
 ]
}